<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEfdu6ie\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEfdu6ie/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEfdu6ie.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEfdu6ie\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEfdu6ie\appProdProjectContainer([
    'container.build_hash' => 'Efdu6ie',
    'container.build_id' => 'dd2cb4ad',
    'container.build_time' => 1672188843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEfdu6ie');
